// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/zoo.proto

package edu.ucla.cs249;

public final class SharedInodeProto {
  private SharedInodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SharedInodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string nodeID = 1;
    boolean hasNodeID();
    String getNodeID();
    
    // required int64 nextVersion = 2;
    boolean hasNextVersion();
    long getNextVersion();
    
    // required string hdfsDir = 3;
    boolean hasHdfsDir();
    String getHdfsDir();
    
    // repeated .cs249.SharedInode.VersionNode existingVersions = 4;
    java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> 
        getExistingVersionsList();
    edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getExistingVersions(int index);
    int getExistingVersionsCount();
    java.util.List<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
        getExistingVersionsOrBuilderList();
    edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder getExistingVersionsOrBuilder(
        int index);
  }
  public static final class SharedInode extends
      com.google.protobuf.GeneratedMessage
      implements SharedInodeOrBuilder {
    // Use SharedInode.newBuilder() to construct.
    private SharedInode(Builder builder) {
      super(builder);
    }
    private SharedInode(boolean noInit) {}
    
    private static final SharedInode defaultInstance;
    public static SharedInode getDefaultInstance() {
      return defaultInstance;
    }
    
    public SharedInode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_fieldAccessorTable;
    }
    
    public interface VersionNodeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int64 version = 1;
      boolean hasVersion();
      long getVersion();
      
      // required string hdfsSubDir = 2;
      boolean hasHdfsSubDir();
      String getHdfsSubDir();
    }
    public static final class VersionNode extends
        com.google.protobuf.GeneratedMessage
        implements VersionNodeOrBuilder {
      // Use VersionNode.newBuilder() to construct.
      private VersionNode(Builder builder) {
        super(builder);
      }
      private VersionNode(boolean noInit) {}
      
      private static final VersionNode defaultInstance;
      public static VersionNode getDefaultInstance() {
        return defaultInstance;
      }
      
      public VersionNode getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int64 version = 1;
      public static final int VERSION_FIELD_NUMBER = 1;
      private long version_;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getVersion() {
        return version_;
      }
      
      // required string hdfsSubDir = 2;
      public static final int HDFSSUBDIR_FIELD_NUMBER = 2;
      private java.lang.Object hdfsSubDir_;
      public boolean hasHdfsSubDir() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getHdfsSubDir() {
        java.lang.Object ref = hdfsSubDir_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            hdfsSubDir_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getHdfsSubDirBytes() {
        java.lang.Object ref = hdfsSubDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          hdfsSubDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        version_ = 0L;
        hdfsSubDir_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasVersion()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHdfsSubDir()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, version_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getHdfsSubDirBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, version_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getHdfsSubDirBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable;
        }
        
        // Construct using edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          version_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          hdfsSubDir_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDescriptor();
        }
        
        public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getDefaultInstanceForType() {
          return edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance();
        }
        
        public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode build() {
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode buildPartial() {
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode result = new edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.version_ = version_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.hdfsSubDir_ = hdfsSubDir_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode) {
            return mergeFrom((edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode other) {
          if (other == edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance()) return this;
          if (other.hasVersion()) {
            setVersion(other.getVersion());
          }
          if (other.hasHdfsSubDir()) {
            setHdfsSubDir(other.getHdfsSubDir());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasVersion()) {
            
            return false;
          }
          if (!hasHdfsSubDir()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                version_ = input.readInt64();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                hdfsSubDir_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int64 version = 1;
        private long version_ ;
        public boolean hasVersion() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public long getVersion() {
          return version_;
        }
        public Builder setVersion(long value) {
          bitField0_ |= 0x00000001;
          version_ = value;
          onChanged();
          return this;
        }
        public Builder clearVersion() {
          bitField0_ = (bitField0_ & ~0x00000001);
          version_ = 0L;
          onChanged();
          return this;
        }
        
        // required string hdfsSubDir = 2;
        private java.lang.Object hdfsSubDir_ = "";
        public boolean hasHdfsSubDir() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getHdfsSubDir() {
          java.lang.Object ref = hdfsSubDir_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            hdfsSubDir_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setHdfsSubDir(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          hdfsSubDir_ = value;
          onChanged();
          return this;
        }
        public Builder clearHdfsSubDir() {
          bitField0_ = (bitField0_ & ~0x00000002);
          hdfsSubDir_ = getDefaultInstance().getHdfsSubDir();
          onChanged();
          return this;
        }
        void setHdfsSubDir(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          hdfsSubDir_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:cs249.SharedInode.VersionNode)
      }
      
      static {
        defaultInstance = new VersionNode(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:cs249.SharedInode.VersionNode)
    }
    
    private int bitField0_;
    // required string nodeID = 1;
    public static final int NODEID_FIELD_NUMBER = 1;
    private java.lang.Object nodeID_;
    public boolean hasNodeID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNodeID() {
      java.lang.Object ref = nodeID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nodeID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNodeIDBytes() {
      java.lang.Object ref = nodeID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nodeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 nextVersion = 2;
    public static final int NEXTVERSION_FIELD_NUMBER = 2;
    private long nextVersion_;
    public boolean hasNextVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getNextVersion() {
      return nextVersion_;
    }
    
    // required string hdfsDir = 3;
    public static final int HDFSDIR_FIELD_NUMBER = 3;
    private java.lang.Object hdfsDir_;
    public boolean hasHdfsDir() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getHdfsDir() {
      java.lang.Object ref = hdfsDir_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hdfsDir_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHdfsDirBytes() {
      java.lang.Object ref = hdfsDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hdfsDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .cs249.SharedInode.VersionNode existingVersions = 4;
    public static final int EXISTINGVERSIONS_FIELD_NUMBER = 4;
    private java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> existingVersions_;
    public java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> getExistingVersionsList() {
      return existingVersions_;
    }
    public java.util.List<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
        getExistingVersionsOrBuilderList() {
      return existingVersions_;
    }
    public int getExistingVersionsCount() {
      return existingVersions_.size();
    }
    public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getExistingVersions(int index) {
      return existingVersions_.get(index);
    }
    public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder getExistingVersionsOrBuilder(
        int index) {
      return existingVersions_.get(index);
    }
    
    private void initFields() {
      nodeID_ = "";
      nextVersion_ = 0L;
      hdfsDir_ = "";
      existingVersions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNodeID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNextVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHdfsDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getExistingVersionsCount(); i++) {
        if (!getExistingVersions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNodeIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, nextVersion_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHdfsDirBytes());
      }
      for (int i = 0; i < existingVersions_.size(); i++) {
        output.writeMessage(4, existingVersions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNodeIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, nextVersion_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHdfsDirBytes());
      }
      for (int i = 0; i < existingVersions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, existingVersions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucla.cs249.SharedInodeProto.SharedInode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucla.cs249.SharedInodeProto.SharedInodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_fieldAccessorTable;
      }
      
      // Construct using edu.ucla.cs249.SharedInodeProto.SharedInode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExistingVersionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nodeID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nextVersion_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        hdfsDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (existingVersionsBuilder_ == null) {
          existingVersions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          existingVersionsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucla.cs249.SharedInodeProto.SharedInode.getDescriptor();
      }
      
      public edu.ucla.cs249.SharedInodeProto.SharedInode getDefaultInstanceForType() {
        return edu.ucla.cs249.SharedInodeProto.SharedInode.getDefaultInstance();
      }
      
      public edu.ucla.cs249.SharedInodeProto.SharedInode build() {
        edu.ucla.cs249.SharedInodeProto.SharedInode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucla.cs249.SharedInodeProto.SharedInode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucla.cs249.SharedInodeProto.SharedInode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucla.cs249.SharedInodeProto.SharedInode buildPartial() {
        edu.ucla.cs249.SharedInodeProto.SharedInode result = new edu.ucla.cs249.SharedInodeProto.SharedInode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeID_ = nodeID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nextVersion_ = nextVersion_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hdfsDir_ = hdfsDir_;
        if (existingVersionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            existingVersions_ = java.util.Collections.unmodifiableList(existingVersions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.existingVersions_ = existingVersions_;
        } else {
          result.existingVersions_ = existingVersionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucla.cs249.SharedInodeProto.SharedInode) {
          return mergeFrom((edu.ucla.cs249.SharedInodeProto.SharedInode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucla.cs249.SharedInodeProto.SharedInode other) {
        if (other == edu.ucla.cs249.SharedInodeProto.SharedInode.getDefaultInstance()) return this;
        if (other.hasNodeID()) {
          setNodeID(other.getNodeID());
        }
        if (other.hasNextVersion()) {
          setNextVersion(other.getNextVersion());
        }
        if (other.hasHdfsDir()) {
          setHdfsDir(other.getHdfsDir());
        }
        if (existingVersionsBuilder_ == null) {
          if (!other.existingVersions_.isEmpty()) {
            if (existingVersions_.isEmpty()) {
              existingVersions_ = other.existingVersions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureExistingVersionsIsMutable();
              existingVersions_.addAll(other.existingVersions_);
            }
            onChanged();
          }
        } else {
          if (!other.existingVersions_.isEmpty()) {
            if (existingVersionsBuilder_.isEmpty()) {
              existingVersionsBuilder_.dispose();
              existingVersionsBuilder_ = null;
              existingVersions_ = other.existingVersions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              existingVersionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExistingVersionsFieldBuilder() : null;
            } else {
              existingVersionsBuilder_.addAllMessages(other.existingVersions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNodeID()) {
          
          return false;
        }
        if (!hasNextVersion()) {
          
          return false;
        }
        if (!hasHdfsDir()) {
          
          return false;
        }
        for (int i = 0; i < getExistingVersionsCount(); i++) {
          if (!getExistingVersions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nodeID_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nextVersion_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              hdfsDir_ = input.readBytes();
              break;
            }
            case 34: {
              edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder subBuilder = edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addExistingVersions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string nodeID = 1;
      private java.lang.Object nodeID_ = "";
      public boolean hasNodeID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNodeID() {
        java.lang.Object ref = nodeID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nodeID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNodeID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeID_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeID_ = getDefaultInstance().getNodeID();
        onChanged();
        return this;
      }
      void setNodeID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        nodeID_ = value;
        onChanged();
      }
      
      // required int64 nextVersion = 2;
      private long nextVersion_ ;
      public boolean hasNextVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getNextVersion() {
        return nextVersion_;
      }
      public Builder setNextVersion(long value) {
        bitField0_ |= 0x00000002;
        nextVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearNextVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nextVersion_ = 0L;
        onChanged();
        return this;
      }
      
      // required string hdfsDir = 3;
      private java.lang.Object hdfsDir_ = "";
      public boolean hasHdfsDir() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getHdfsDir() {
        java.lang.Object ref = hdfsDir_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hdfsDir_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHdfsDir(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hdfsDir_ = value;
        onChanged();
        return this;
      }
      public Builder clearHdfsDir() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hdfsDir_ = getDefaultInstance().getHdfsDir();
        onChanged();
        return this;
      }
      void setHdfsDir(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        hdfsDir_ = value;
        onChanged();
      }
      
      // repeated .cs249.SharedInode.VersionNode existingVersions = 4;
      private java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> existingVersions_ =
        java.util.Collections.emptyList();
      private void ensureExistingVersionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          existingVersions_ = new java.util.ArrayList<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode>(existingVersions_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> existingVersionsBuilder_;
      
      public java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> getExistingVersionsList() {
        if (existingVersionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(existingVersions_);
        } else {
          return existingVersionsBuilder_.getMessageList();
        }
      }
      public int getExistingVersionsCount() {
        if (existingVersionsBuilder_ == null) {
          return existingVersions_.size();
        } else {
          return existingVersionsBuilder_.getCount();
        }
      }
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getExistingVersions(int index) {
        if (existingVersionsBuilder_ == null) {
          return existingVersions_.get(index);
        } else {
          return existingVersionsBuilder_.getMessage(index);
        }
      }
      public Builder setExistingVersions(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode value) {
        if (existingVersionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExistingVersionsIsMutable();
          existingVersions_.set(index, value);
          onChanged();
        } else {
          existingVersionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setExistingVersions(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder builderForValue) {
        if (existingVersionsBuilder_ == null) {
          ensureExistingVersionsIsMutable();
          existingVersions_.set(index, builderForValue.build());
          onChanged();
        } else {
          existingVersionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addExistingVersions(edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode value) {
        if (existingVersionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExistingVersionsIsMutable();
          existingVersions_.add(value);
          onChanged();
        } else {
          existingVersionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addExistingVersions(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode value) {
        if (existingVersionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExistingVersionsIsMutable();
          existingVersions_.add(index, value);
          onChanged();
        } else {
          existingVersionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addExistingVersions(
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder builderForValue) {
        if (existingVersionsBuilder_ == null) {
          ensureExistingVersionsIsMutable();
          existingVersions_.add(builderForValue.build());
          onChanged();
        } else {
          existingVersionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addExistingVersions(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder builderForValue) {
        if (existingVersionsBuilder_ == null) {
          ensureExistingVersionsIsMutable();
          existingVersions_.add(index, builderForValue.build());
          onChanged();
        } else {
          existingVersionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllExistingVersions(
          java.lang.Iterable<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> values) {
        if (existingVersionsBuilder_ == null) {
          ensureExistingVersionsIsMutable();
          super.addAll(values, existingVersions_);
          onChanged();
        } else {
          existingVersionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearExistingVersions() {
        if (existingVersionsBuilder_ == null) {
          existingVersions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          existingVersionsBuilder_.clear();
        }
        return this;
      }
      public Builder removeExistingVersions(int index) {
        if (existingVersionsBuilder_ == null) {
          ensureExistingVersionsIsMutable();
          existingVersions_.remove(index);
          onChanged();
        } else {
          existingVersionsBuilder_.remove(index);
        }
        return this;
      }
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder getExistingVersionsBuilder(
          int index) {
        return getExistingVersionsFieldBuilder().getBuilder(index);
      }
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder getExistingVersionsOrBuilder(
          int index) {
        if (existingVersionsBuilder_ == null) {
          return existingVersions_.get(index);  } else {
          return existingVersionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
           getExistingVersionsOrBuilderList() {
        if (existingVersionsBuilder_ != null) {
          return existingVersionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(existingVersions_);
        }
      }
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder addExistingVersionsBuilder() {
        return getExistingVersionsFieldBuilder().addBuilder(
            edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance());
      }
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder addExistingVersionsBuilder(
          int index) {
        return getExistingVersionsFieldBuilder().addBuilder(
            index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance());
      }
      public java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder> 
           getExistingVersionsBuilderList() {
        return getExistingVersionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
          getExistingVersionsFieldBuilder() {
        if (existingVersionsBuilder_ == null) {
          existingVersionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder>(
                  existingVersions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          existingVersions_ = null;
        }
        return existingVersionsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cs249.SharedInode)
    }
    
    static {
      defaultInstance = new SharedInode(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cs249.SharedInode)
  }
  
  public interface SharedVersionNodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 numReaders = 1;
    boolean hasNumReaders();
    int getNumReaders();
  }
  public static final class SharedVersionNode extends
      com.google.protobuf.GeneratedMessage
      implements SharedVersionNodeOrBuilder {
    // Use SharedVersionNode.newBuilder() to construct.
    private SharedVersionNode(Builder builder) {
      super(builder);
    }
    private SharedVersionNode(boolean noInit) {}
    
    private static final SharedVersionNode defaultInstance;
    public static SharedVersionNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public SharedVersionNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedVersionNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedVersionNode_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 numReaders = 1;
    public static final int NUMREADERS_FIELD_NUMBER = 1;
    private int numReaders_;
    public boolean hasNumReaders() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getNumReaders() {
      return numReaders_;
    }
    
    private void initFields() {
      numReaders_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNumReaders()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, numReaders_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numReaders_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedVersionNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucla.cs249.SharedInodeProto.SharedVersionNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucla.cs249.SharedInodeProto.SharedVersionNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedVersionNode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedVersionNode_fieldAccessorTable;
      }
      
      // Construct using edu.ucla.cs249.SharedInodeProto.SharedVersionNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        numReaders_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucla.cs249.SharedInodeProto.SharedVersionNode.getDescriptor();
      }
      
      public edu.ucla.cs249.SharedInodeProto.SharedVersionNode getDefaultInstanceForType() {
        return edu.ucla.cs249.SharedInodeProto.SharedVersionNode.getDefaultInstance();
      }
      
      public edu.ucla.cs249.SharedInodeProto.SharedVersionNode build() {
        edu.ucla.cs249.SharedInodeProto.SharedVersionNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucla.cs249.SharedInodeProto.SharedVersionNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucla.cs249.SharedInodeProto.SharedVersionNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucla.cs249.SharedInodeProto.SharedVersionNode buildPartial() {
        edu.ucla.cs249.SharedInodeProto.SharedVersionNode result = new edu.ucla.cs249.SharedInodeProto.SharedVersionNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.numReaders_ = numReaders_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucla.cs249.SharedInodeProto.SharedVersionNode) {
          return mergeFrom((edu.ucla.cs249.SharedInodeProto.SharedVersionNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucla.cs249.SharedInodeProto.SharedVersionNode other) {
        if (other == edu.ucla.cs249.SharedInodeProto.SharedVersionNode.getDefaultInstance()) return this;
        if (other.hasNumReaders()) {
          setNumReaders(other.getNumReaders());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNumReaders()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              numReaders_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 numReaders = 1;
      private int numReaders_ ;
      public boolean hasNumReaders() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getNumReaders() {
        return numReaders_;
      }
      public Builder setNumReaders(int value) {
        bitField0_ |= 0x00000001;
        numReaders_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumReaders() {
        bitField0_ = (bitField0_ & ~0x00000001);
        numReaders_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cs249.SharedVersionNode)
    }
    
    static {
      defaultInstance = new SharedVersionNode(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cs249.SharedVersionNode)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cs249_SharedInode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cs249_SharedInode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cs249_SharedInode_VersionNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cs249_SharedVersionNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cs249_SharedVersionNode_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/zoo.proto\022\005cs249\"\261\001\n\013SharedInode" +
      "\022\016\n\006nodeID\030\001 \002(\t\022\023\n\013nextVersion\030\002 \002(\003\022\017\n" +
      "\007hdfsDir\030\003 \002(\t\0228\n\020existingVersions\030\004 \003(\013" +
      "2\036.cs249.SharedInode.VersionNode\0322\n\013Vers" +
      "ionNode\022\017\n\007version\030\001 \002(\003\022\022\n\nhdfsSubDir\030\002" +
      " \002(\t\"\'\n\021SharedVersionNode\022\022\n\nnumReaders\030" +
      "\001 \002(\005B\"\n\016edu.ucla.cs249B\020SharedInodeProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cs249_SharedInode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cs249_SharedInode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cs249_SharedInode_descriptor,
              new java.lang.String[] { "NodeID", "NextVersion", "HdfsDir", "ExistingVersions", },
              edu.ucla.cs249.SharedInodeProto.SharedInode.class,
              edu.ucla.cs249.SharedInodeProto.SharedInode.Builder.class);
          internal_static_cs249_SharedInode_VersionNode_descriptor =
            internal_static_cs249_SharedInode_descriptor.getNestedTypes().get(0);
          internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cs249_SharedInode_VersionNode_descriptor,
              new java.lang.String[] { "Version", "HdfsSubDir", },
              edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.class,
              edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder.class);
          internal_static_cs249_SharedVersionNode_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cs249_SharedVersionNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cs249_SharedVersionNode_descriptor,
              new java.lang.String[] { "NumReaders", },
              edu.ucla.cs249.SharedInodeProto.SharedVersionNode.class,
              edu.ucla.cs249.SharedInodeProto.SharedVersionNode.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
