// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/zoo.proto

package edu.ucla.cs249;

public final class SharedInodeProto {
  private SharedInodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SharedInodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 nextVersion = 1;
    /**
     * <code>required int64 nextVersion = 1;</code>
     */
    boolean hasNextVersion();
    /**
     * <code>required int64 nextVersion = 1;</code>
     */
    long getNextVersion();

    // repeated .cs249.SharedInode.VersionNode reads = 2;
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> 
        getReadsList();
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getReads(int index);
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    int getReadsCount();
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    java.util.List<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
        getReadsOrBuilderList();
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder getReadsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cs249.SharedInode}
   */
  public static final class SharedInode extends
      com.google.protobuf.GeneratedMessage
      implements SharedInodeOrBuilder {
    // Use SharedInode.newBuilder() to construct.
    private SharedInode(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SharedInode(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SharedInode defaultInstance;
    public static SharedInode getDefaultInstance() {
      return defaultInstance;
    }

    public SharedInode getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SharedInode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nextVersion_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                reads_ = new java.util.ArrayList<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode>();
                mutable_bitField0_ |= 0x00000002;
              }
              reads_.add(input.readMessage(edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          reads_ = java.util.Collections.unmodifiableList(reads_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.ucla.cs249.SharedInodeProto.SharedInode.class, edu.ucla.cs249.SharedInodeProto.SharedInode.Builder.class);
    }

    public static com.google.protobuf.Parser<SharedInode> PARSER =
        new com.google.protobuf.AbstractParser<SharedInode>() {
      public SharedInode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SharedInode(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SharedInode> getParserForType() {
      return PARSER;
    }

    public interface VersionNodeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int64 version = 1;
      /**
       * <code>required int64 version = 1;</code>
       */
      boolean hasVersion();
      /**
       * <code>required int64 version = 1;</code>
       */
      long getVersion();

      // required int32 numReaders = 2;
      /**
       * <code>required int32 numReaders = 2;</code>
       */
      boolean hasNumReaders();
      /**
       * <code>required int32 numReaders = 2;</code>
       */
      int getNumReaders();
    }
    /**
     * Protobuf type {@code cs249.SharedInode.VersionNode}
     */
    public static final class VersionNode extends
        com.google.protobuf.GeneratedMessage
        implements VersionNodeOrBuilder {
      // Use VersionNode.newBuilder() to construct.
      private VersionNode(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private VersionNode(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final VersionNode defaultInstance;
      public static VersionNode getDefaultInstance() {
        return defaultInstance;
      }

      public VersionNode getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private VersionNode(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                version_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                numReaders_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.class, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder.class);
      }

      public static com.google.protobuf.Parser<VersionNode> PARSER =
          new com.google.protobuf.AbstractParser<VersionNode>() {
        public VersionNode parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new VersionNode(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<VersionNode> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int64 version = 1;
      public static final int VERSION_FIELD_NUMBER = 1;
      private long version_;
      /**
       * <code>required int64 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 version = 1;</code>
       */
      public long getVersion() {
        return version_;
      }

      // required int32 numReaders = 2;
      public static final int NUMREADERS_FIELD_NUMBER = 2;
      private int numReaders_;
      /**
       * <code>required int32 numReaders = 2;</code>
       */
      public boolean hasNumReaders() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 numReaders = 2;</code>
       */
      public int getNumReaders() {
        return numReaders_;
      }

      private void initFields() {
        version_ = 0L;
        numReaders_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasVersion()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNumReaders()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, version_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, numReaders_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, version_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, numReaders_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code cs249.SharedInode.VersionNode}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.class, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder.class);
        }

        // Construct using edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          version_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          numReaders_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_VersionNode_descriptor;
        }

        public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getDefaultInstanceForType() {
          return edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance();
        }

        public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode build() {
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode buildPartial() {
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode result = new edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.version_ = version_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.numReaders_ = numReaders_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode) {
            return mergeFrom((edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode other) {
          if (other == edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance()) return this;
          if (other.hasVersion()) {
            setVersion(other.getVersion());
          }
          if (other.hasNumReaders()) {
            setNumReaders(other.getNumReaders());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasVersion()) {
            
            return false;
          }
          if (!hasNumReaders()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int64 version = 1;
        private long version_ ;
        /**
         * <code>required int64 version = 1;</code>
         */
        public boolean hasVersion() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 version = 1;</code>
         */
        public long getVersion() {
          return version_;
        }
        /**
         * <code>required int64 version = 1;</code>
         */
        public Builder setVersion(long value) {
          bitField0_ |= 0x00000001;
          version_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 version = 1;</code>
         */
        public Builder clearVersion() {
          bitField0_ = (bitField0_ & ~0x00000001);
          version_ = 0L;
          onChanged();
          return this;
        }

        // required int32 numReaders = 2;
        private int numReaders_ ;
        /**
         * <code>required int32 numReaders = 2;</code>
         */
        public boolean hasNumReaders() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 numReaders = 2;</code>
         */
        public int getNumReaders() {
          return numReaders_;
        }
        /**
         * <code>required int32 numReaders = 2;</code>
         */
        public Builder setNumReaders(int value) {
          bitField0_ |= 0x00000002;
          numReaders_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 numReaders = 2;</code>
         */
        public Builder clearNumReaders() {
          bitField0_ = (bitField0_ & ~0x00000002);
          numReaders_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:cs249.SharedInode.VersionNode)
      }

      static {
        defaultInstance = new VersionNode(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:cs249.SharedInode.VersionNode)
    }

    private int bitField0_;
    // required int64 nextVersion = 1;
    public static final int NEXTVERSION_FIELD_NUMBER = 1;
    private long nextVersion_;
    /**
     * <code>required int64 nextVersion = 1;</code>
     */
    public boolean hasNextVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 nextVersion = 1;</code>
     */
    public long getNextVersion() {
      return nextVersion_;
    }

    // repeated .cs249.SharedInode.VersionNode reads = 2;
    public static final int READS_FIELD_NUMBER = 2;
    private java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> reads_;
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    public java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> getReadsList() {
      return reads_;
    }
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    public java.util.List<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
        getReadsOrBuilderList() {
      return reads_;
    }
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    public int getReadsCount() {
      return reads_.size();
    }
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getReads(int index) {
      return reads_.get(index);
    }
    /**
     * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
     */
    public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder getReadsOrBuilder(
        int index) {
      return reads_.get(index);
    }

    private void initFields() {
      nextVersion_ = 0L;
      reads_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNextVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getReadsCount(); i++) {
        if (!getReads(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, nextVersion_);
      }
      for (int i = 0; i < reads_.size(); i++) {
        output.writeMessage(2, reads_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nextVersion_);
      }
      for (int i = 0; i < reads_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, reads_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.ucla.cs249.SharedInodeProto.SharedInode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucla.cs249.SharedInodeProto.SharedInode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cs249.SharedInode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucla.cs249.SharedInodeProto.SharedInodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.ucla.cs249.SharedInodeProto.SharedInode.class, edu.ucla.cs249.SharedInodeProto.SharedInode.Builder.class);
      }

      // Construct using edu.ucla.cs249.SharedInodeProto.SharedInode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReadsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nextVersion_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (readsBuilder_ == null) {
          reads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          readsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucla.cs249.SharedInodeProto.internal_static_cs249_SharedInode_descriptor;
      }

      public edu.ucla.cs249.SharedInodeProto.SharedInode getDefaultInstanceForType() {
        return edu.ucla.cs249.SharedInodeProto.SharedInode.getDefaultInstance();
      }

      public edu.ucla.cs249.SharedInodeProto.SharedInode build() {
        edu.ucla.cs249.SharedInodeProto.SharedInode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.ucla.cs249.SharedInodeProto.SharedInode buildPartial() {
        edu.ucla.cs249.SharedInodeProto.SharedInode result = new edu.ucla.cs249.SharedInodeProto.SharedInode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nextVersion_ = nextVersion_;
        if (readsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            reads_ = java.util.Collections.unmodifiableList(reads_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.reads_ = reads_;
        } else {
          result.reads_ = readsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucla.cs249.SharedInodeProto.SharedInode) {
          return mergeFrom((edu.ucla.cs249.SharedInodeProto.SharedInode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.ucla.cs249.SharedInodeProto.SharedInode other) {
        if (other == edu.ucla.cs249.SharedInodeProto.SharedInode.getDefaultInstance()) return this;
        if (other.hasNextVersion()) {
          setNextVersion(other.getNextVersion());
        }
        if (readsBuilder_ == null) {
          if (!other.reads_.isEmpty()) {
            if (reads_.isEmpty()) {
              reads_ = other.reads_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureReadsIsMutable();
              reads_.addAll(other.reads_);
            }
            onChanged();
          }
        } else {
          if (!other.reads_.isEmpty()) {
            if (readsBuilder_.isEmpty()) {
              readsBuilder_.dispose();
              readsBuilder_ = null;
              reads_ = other.reads_;
              bitField0_ = (bitField0_ & ~0x00000002);
              readsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReadsFieldBuilder() : null;
            } else {
              readsBuilder_.addAllMessages(other.reads_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNextVersion()) {
          
          return false;
        }
        for (int i = 0; i < getReadsCount(); i++) {
          if (!getReads(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.ucla.cs249.SharedInodeProto.SharedInode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.ucla.cs249.SharedInodeProto.SharedInode) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 nextVersion = 1;
      private long nextVersion_ ;
      /**
       * <code>required int64 nextVersion = 1;</code>
       */
      public boolean hasNextVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 nextVersion = 1;</code>
       */
      public long getNextVersion() {
        return nextVersion_;
      }
      /**
       * <code>required int64 nextVersion = 1;</code>
       */
      public Builder setNextVersion(long value) {
        bitField0_ |= 0x00000001;
        nextVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 nextVersion = 1;</code>
       */
      public Builder clearNextVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nextVersion_ = 0L;
        onChanged();
        return this;
      }

      // repeated .cs249.SharedInode.VersionNode reads = 2;
      private java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> reads_ =
        java.util.Collections.emptyList();
      private void ensureReadsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          reads_ = new java.util.ArrayList<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode>(reads_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> readsBuilder_;

      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> getReadsList() {
        if (readsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reads_);
        } else {
          return readsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public int getReadsCount() {
        if (readsBuilder_ == null) {
          return reads_.size();
        } else {
          return readsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode getReads(int index) {
        if (readsBuilder_ == null) {
          return reads_.get(index);
        } else {
          return readsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder setReads(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode value) {
        if (readsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadsIsMutable();
          reads_.set(index, value);
          onChanged();
        } else {
          readsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder setReads(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder builderForValue) {
        if (readsBuilder_ == null) {
          ensureReadsIsMutable();
          reads_.set(index, builderForValue.build());
          onChanged();
        } else {
          readsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder addReads(edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode value) {
        if (readsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadsIsMutable();
          reads_.add(value);
          onChanged();
        } else {
          readsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder addReads(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode value) {
        if (readsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadsIsMutable();
          reads_.add(index, value);
          onChanged();
        } else {
          readsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder addReads(
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder builderForValue) {
        if (readsBuilder_ == null) {
          ensureReadsIsMutable();
          reads_.add(builderForValue.build());
          onChanged();
        } else {
          readsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder addReads(
          int index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder builderForValue) {
        if (readsBuilder_ == null) {
          ensureReadsIsMutable();
          reads_.add(index, builderForValue.build());
          onChanged();
        } else {
          readsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder addAllReads(
          java.lang.Iterable<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode> values) {
        if (readsBuilder_ == null) {
          ensureReadsIsMutable();
          super.addAll(values, reads_);
          onChanged();
        } else {
          readsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder clearReads() {
        if (readsBuilder_ == null) {
          reads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          readsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public Builder removeReads(int index) {
        if (readsBuilder_ == null) {
          ensureReadsIsMutable();
          reads_.remove(index);
          onChanged();
        } else {
          readsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder getReadsBuilder(
          int index) {
        return getReadsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder getReadsOrBuilder(
          int index) {
        if (readsBuilder_ == null) {
          return reads_.get(index);  } else {
          return readsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public java.util.List<? extends edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
           getReadsOrBuilderList() {
        if (readsBuilder_ != null) {
          return readsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reads_);
        }
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder addReadsBuilder() {
        return getReadsFieldBuilder().addBuilder(
            edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance());
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder addReadsBuilder(
          int index) {
        return getReadsFieldBuilder().addBuilder(
            index, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.getDefaultInstance());
      }
      /**
       * <code>repeated .cs249.SharedInode.VersionNode reads = 2;</code>
       */
      public java.util.List<edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder> 
           getReadsBuilderList() {
        return getReadsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder> 
          getReadsFieldBuilder() {
        if (readsBuilder_ == null) {
          readsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNode.Builder, edu.ucla.cs249.SharedInodeProto.SharedInode.VersionNodeOrBuilder>(
                  reads_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          reads_ = null;
        }
        return readsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cs249.SharedInode)
    }

    static {
      defaultInstance = new SharedInode(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cs249.SharedInode)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cs249_SharedInode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cs249_SharedInode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cs249_SharedInode_VersionNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/zoo.proto\022\005cs249\"\205\001\n\013SharedInode" +
      "\022\023\n\013nextVersion\030\001 \002(\003\022-\n\005reads\030\002 \003(\0132\036.c" +
      "s249.SharedInode.VersionNode\0322\n\013VersionN" +
      "ode\022\017\n\007version\030\001 \002(\003\022\022\n\nnumReaders\030\002 \002(\005" +
      "B\"\n\016edu.ucla.cs249B\020SharedInodeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cs249_SharedInode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cs249_SharedInode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cs249_SharedInode_descriptor,
              new java.lang.String[] { "NextVersion", "Reads", });
          internal_static_cs249_SharedInode_VersionNode_descriptor =
            internal_static_cs249_SharedInode_descriptor.getNestedTypes().get(0);
          internal_static_cs249_SharedInode_VersionNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cs249_SharedInode_VersionNode_descriptor,
              new java.lang.String[] { "Version", "NumReaders", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
